{"name": "test_login_with_valid_credentials", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('log_on_failure', <FixtureRequest for <Function test_login_with_valid_credentials>>)", "trace": "file /Users/anashuhada/PycharmProjects/SeleniumWithPython/tutorialsninja/test_Login.py, line 9\n      def test_login_with_valid_credentials(self):\nE       fixture 'log_on_failure' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, capture_failure_screenshot, doctest_namespace, extra, extras, include_metadata_in_junit_xml, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, setup_and_teardown, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id\n>       use 'pytest --fixtures [testpath]' for help on them.\n\n/Users/anashuhada/PycharmProjects/SeleniumWithPython/tutorialsninja/test_Login.py:9"}, "attachments": [{"name": "log", "source": "5cf6b327-34b0-47e7-8d2e-1659989eee52-attachment.txt", "type": "text/plain"}], "start": 1748582203487, "stop": 1748582203487, "uuid": "91b1b6a2-8c38-486f-b0fe-32611577c446", "historyId": "51577eace49c2eba168c9887880045da", "testCaseId": "51577eace49c2eba168c9887880045da", "fullName": "tutorialsninja.test_Login.TestLogin#test_login_with_valid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tutorialsninja"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Macmini"}, {"name": "thread", "value": "5494-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tutorialsninja.test_Login"}]}