{"uuid": "98599a33-6761-49d2-ae57-4e062d0020df", "children": ["9bade090-1b1d-4967-8c1f-c79b205be075"], "befores": [{"name": "capture_failure_screenshot", "status": "passed", "start": 1748581266293, "stop": 1748581266293}], "afters": [{"name": "capture_failure_screenshot::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/tutorialsninja/conftest.py\", line 32, in capture_failure_screenshot\n    if request.node.rep_call.failed:\n       ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1748581266293, "stop": 1748581266293}], "start": 1748581266293, "stop": 1748581266293}