{"uuid": "af79f4c3-bf1f-49b2-a07b-373f3cf8deec", "children": ["37396c12-2137-4f61-81d9-e7ce96dad7fd"], "befores": [{"name": "capture_failure_screenshot", "status": "passed", "start": 1748581940200, "stop": 1748581940200}], "afters": [{"name": "capture_failure_screenshot::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/tutorialsninja/conftest.py\", line 32, in capture_failure_screenshot\n    if request.node.rep_call.failed:\n       ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1748581944999, "stop": 1748581944999}], "start": 1748581940200, "stop": 1748581944999}